name: disp-s1-env
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - click>=7.0
  - isce3>=0.16.0
  - dolphin>=0.15.3
  - h5netcdf>=1.0
  - snaphu>=0.2.1
  - pillow>=7.0
  - pydantic>=2.1
  - ruamel.yaml>=0.15
  - tophu>=0.2.0
  - yamale
